import type { Metadata } from "next";
import { Moulpali} from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Script from "next/script";
import Header from "@/components/Header";
const Font = Moulpali({
  subsets :["latin"],
  weight :['400']
}) 

import { Provider } from "react-redux";
import Footer from "@/components/Footer";
import store from "@/redux/store";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={Font.className}
      >
       <Provider store={store}>
        <Header />
        {children}
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" />
        <Footer/>
        </Provider>
      </body>
    </html>
  );
}
